# Lab | Web Scraping Multiple Pages

- Business goal:
Check the case_study_gnod.md file.

Make sure you've understood the big picture of your project:

- the goal of the company (Gnod),
- their current product (Gnoosic),
- their strategy, and
- how your project fits into this context.


Re-read the business case and the e-mail from the CTO, take a look at the flowchart and create an initial Trello board with the tasks you think you'll have to accomplish.

## Instructions Part 1

Prioritize the MVP (Minimum Viable Product)


In the previous lab, you had to scrape data about "hot songs". It's critical to be on track with that part, as it was part of the request from the CTO.

If you couldn't finish the first lab, use this time to go back there.

### Expand the project
If you're done, you can try to expand the project on your own. Here are a few suggestions:

- Find other lists of hot songs on the internet and scrape them too: having a bigger pool of songs will be awesome!
- Apply the same logic to other "groups" of songs: the best songs from a decade or from a country / culture / language / genre.
Wikipedia maintains a large collection of lists of songs: https://en.wikipedia.org/wiki/Lists_of_songs

### Instructions Part 2
Practice web scraping. This is not involved with the GNOD project of the week
As you've seen, scraping the internet is a skill that can get you all sorts of information. Here are some little challenges that you can try to gain more experience in the field. Open a new Jupyter notebook and scrape at least 3 of these sites.

In [1]:
# Libraries
import pandas as pd
import requests
from bs4 import BeautifulSoup
from time import sleep
import random
from random import randint

#### 1. Retrieve an arbitrary Wikipedia page of "Python" and create a list of links on that page: url ='https://en.wikipedia.org/wiki/Python'

In [2]:
url = 'https://en.wikipedia.org/wiki/Python'
response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')

display(response.status_code)

200

In [3]:
#links --> #mw-content-text > div.mw-parser-output > ul:nth-child(7) > li:nth-child(1) > a

In [5]:
pytab =soup.select("#mw-content-text > div.mw-parser-output a")
pytab

[<a class="extiw" href="https://en.wiktionary.org/wiki/Python" title="wiktionary:Python">Python</a>,
 <a class="extiw" href="https://en.wiktionary.org/wiki/python" title="wiktionary:python">python</a>,
 <a href="/w/index.php?title=Python&amp;action=edit&amp;section=1" title="Edit section: Snakes">edit</a>,
 <a href="/wiki/Pythonidae" title="Pythonidae">Pythonidae</a>,
 <a href="/wiki/Python_(genus)" title="Python (genus)"><i>Python</i> (genus)</a>,
 <a href="/wiki/Python_(mythology)" title="Python (mythology)">Python (mythology)</a>,
 <a href="/w/index.php?title=Python&amp;action=edit&amp;section=2" title="Edit section: Computing">edit</a>,
 <a href="/wiki/Python_(programming_language)" title="Python (programming language)">Python (programming language)</a>,
 <a href="/wiki/CMU_Common_Lisp" title="CMU Common Lisp">CMU Common Lisp</a>,
 <a href="/wiki/PERQ#PERQ_3" title="PERQ">PERQ 3</a>,
 <a href="/w/index.php?title=Python&amp;action=edit&amp;section=3" title="Edit section: People">edit</a>,
 <a href="/wiki/Python_of_Aenus" title="Python of Aenus">Python of Aenus</a>,
 <a href="/wiki/Python_(painter)" title="Python (painter)">Python (painter)</a>,
 <a href="/wiki/Python_of_Byzantium" title="Python of Byzantium">Python of Byzantium</a>,
 <a href="/wiki/Python_of_Catana" title="Python of Catana">Python of Catana</a>,
 <a href="/wiki/Python_Anghelo" title="Python Anghelo">Python Anghelo</a>,
 <a href="/w/index.php?title=Python&amp;action=edit&amp;section=4" title="Edit section: Roller coasters">edit</a>,
 <a href="/wiki/Python_(Efteling)" title="Python (Efteling)">Python (Efteling)</a>,
 <a href="/wiki/Python_(Busch_Gardens_Tampa_Bay)" title="Python (Busch Gardens Tampa Bay)">Python (Busch Gardens Tampa Bay)</a>,
 <a href="/wiki/Python_(Coney_Island,_Cincinnati,_Ohio)" title="Python (Coney Island, Cincinnati, Ohio)">Python (Coney Island, Cincinnati, Ohio)</a>,
 <a href="/w/index.php?title=Python&amp;action=edit&amp;section=5" title="Edit section: Vehicles">edit</a>,
 <a href="/wiki/Python_(automobile_maker)" title="Python (automobile maker)">Python (automobile maker)</a>,
 <a href="/wiki/Python_(Ford_prototype)" title="Python (Ford prototype)">Python (Ford prototype)</a>,
 <a href="/w/index.php?title=Python&amp;action=edit&amp;section=6" title="Edit section: Weaponry">edit</a>,
 <a href="/wiki/Python_(missile)" title="Python (missile)">Python (missile)</a>,
 <a href="/wiki/Python_(nuclear_primary)" title="Python (nuclear primary)">Python (nuclear primary)</a>,
 <a href="/wiki/Colt_Python" title="Colt Python">Colt Python</a>,
 <a href="/w/index.php?title=Python&amp;action=edit&amp;section=7" title="Edit section: Other uses">edit</a>,
 <a href="/wiki/Python_(codename)" title="Python (codename)">Python (codename)</a>,
 <a href="/wiki/Python_(film)" title="Python (film)"><i>Python</i> (film)</a>,
 <a href="/wiki/Monty_Python" title="Monty Python">Monty Python</a>,
 <a href="/wiki/Python_(Monty)_Pictures" title="Python (Monty) Pictures">Python (Monty) Pictures</a>,
 <a href="/wiki/Timon_of_Phlius" title="Timon of Phlius">Timon of Phlius</a>,
 <a href="/w/index.php?title=Python&amp;action=edit&amp;section=8" title="Edit section: See also">edit</a>,
 <a href="/wiki/Pyton" title="Pyton">Pyton</a>,
 <a href="/wiki/Pithon" title="Pithon">Pithon</a>,
 <a class="image" href="/wiki/File:Disambig_gray.svg"><img alt="Disambiguation icon" data-file-height="168" data-file-width="220" decoding="async" height="23" src="//upload.wikimedia.org/wikipedia/en/thumb/5/5f/Disambig_gray.svg/30px-Disambig_gray.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/5/5f/Disambig_gray.svg/45px-Disambig_gray.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/5/5f/Disambig_gray.svg/60px-Disambig_gray.svg.png 2x" width="30"/></a>,
 <a href="/wiki/Help:Disambiguation" title="Help:Disambiguation">disambiguation</a>,
 <a class="external text" href="https://en.wikipedia.org/w/index.php?title=Special:WhatLinksHere/Python&amp;namespace=0">internal link</a>]

In [17]:
link_list = []
for py in pytab:
    link = py.get("href")
    if link is not None:
        if (("/wiki/" in link)&
            ("/en.wiktionary.org/" not in link)&
            (":Disambig" not in link)): 
            link_list.append(py["href"])

            
print(len(link), len(link_list))
print(link_list)

83 26
['/wiki/Pythonidae', '/wiki/Python_(genus)', '/wiki/Python_(mythology)', '/wiki/Python_(programming_language)', '/wiki/CMU_Common_Lisp', '/wiki/PERQ#PERQ_3', '/wiki/Python_of_Aenus', '/wiki/Python_(painter)', '/wiki/Python_of_Byzantium', '/wiki/Python_of_Catana', '/wiki/Python_Anghelo', '/wiki/Python_(Efteling)', '/wiki/Python_(Busch_Gardens_Tampa_Bay)', '/wiki/Python_(Coney_Island,_Cincinnati,_Ohio)', '/wiki/Python_(automobile_maker)', '/wiki/Python_(Ford_prototype)', '/wiki/Python_(missile)', '/wiki/Python_(nuclear_primary)', '/wiki/Colt_Python', '/wiki/Python_(codename)', '/wiki/Python_(film)', '/wiki/Monty_Python', '/wiki/Python_(Monty)_Pictures', '/wiki/Timon_of_Phlius', '/wiki/Pyton', '/wiki/Pithon']

In [14]:
links = pd.DataFrame({"links":link_list})
links

                                            links
0                                /wiki/Pythonidae
1                            /wiki/Python_(genus)
2                        /wiki/Python_(mythology)
3             /wiki/Python_(programming_language)
4                           /wiki/CMU_Common_Lisp
5                               /wiki/PERQ#PERQ_3
6                           /wiki/Python_of_Aenus
7                          /wiki/Python_(painter)
8                       /wiki/Python_of_Byzantium
9                          /wiki/Python_of_Catana
10                           /wiki/Python_Anghelo
11                        /wiki/Python_(Efteling)
12         /wiki/Python_(Busch_Gardens_Tampa_Bay)
13  /wiki/Python_(Coney_Island,_Cincinnati,_Ohio)
14                /wiki/Python_(automobile_maker)
15                  /wiki/Python_(Ford_prototype)
16                         /wiki/Python_(missile)
17                 /wiki/Python_(nuclear_primary)
18                              /wiki/Colt_Python
19                        /wiki/Python_(codename)
20                            /wiki/Python_(film)
21                             /wiki/Monty_Python
22                  /wiki/Python_(Monty)_Pictures
23                          /wiki/Timon_of_Phlius
24                                    /wiki/Pyton
25                                   /wiki/Pithon

#### 2. Create a Python list with the top ten FBI's Most Wanted names: url = 'https://www.fbi.gov/wanted/topten'

In [18]:
url = 'https://www.fbi.gov/wanted/topten'
response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')

display(response.status_code)
#soup

200

In [19]:
#query-results-0f737222c5054a81a120bce207b0446a > ul > li:nth-child(1) > h3 > a
soup.select("h3")[0:10]

[<h3 class="title">
 <a href="https://www.fbi.gov/wanted/topten/omar-alexander-cardenas">OMAR ALEXANDER CARDENAS</a>
 </h3>,
 <h3 class="title">
 <a href="https://www.fbi.gov/wanted/topten/alexis-flores">ALEXIS FLORES</a>
 </h3>,
 <h3 class="title">
 <a href="https://www.fbi.gov/wanted/topten/bhadreshkumar-chetanbhai-patel">BHADRESHKUMAR CHETANBHAI PATEL</a>
 </h3>,
 <h3 class="title">
 <a href="https://www.fbi.gov/wanted/topten/alejandro-castillo">ALEJANDRO ROSALES CASTILLO</a>
 </h3>,
 <h3 class="title">
 <a href="https://www.fbi.gov/wanted/topten/yulan-adonay-archaga-carias">YULAN ADONAY ARCHAGA CARIAS</a>
 </h3>,
 <h3 class="title">
 <a href="https://www.fbi.gov/wanted/topten/ruja-ignatova">RUJA IGNATOVA</a>
 </h3>,
 <h3 class="title">
 <a href="https://www.fbi.gov/wanted/topten/arnoldo-jimenez">ARNOLDO JIMENEZ</a>
 </h3>,
 <h3 class="title">
 <a href="https://www.fbi.gov/wanted/topten/michael-james-pratt">MICHAEL JAMES PRATT</a>
 </h3>,
 <h3 class="title">
 <a href="https://www.fbi.gov/wanted/topten/jose-rodolfo-villarreal-hernandez">JOSE RODOLFO VILLARREAL-HERNANDEZ</a>
 </h3>,
 <h3 class="title">
 <a href="https://www.fbi.gov/wanted/topten/rafael-caro-quintero">RAFAEL CARO-QUINTERO</a>
 </h3>]

In [20]:
top = []

# Iterations
num_iter = len(soup.select("h3 a"))

top_top = soup.select("h3 a")

for i in range(num_iter):
    top.append(top_top[i].get_text())
    
print(top[0:10])

['OMAR ALEXANDER CARDENAS', 'ALEXIS FLORES', 'BHADRESHKUMAR CHETANBHAI PATEL', 'ALEJANDRO ROSALES CASTILLO', 'YULAN ADONAY ARCHAGA CARIAS', 'RUJA IGNATOVA', 'ARNOLDO JIMENEZ', 'MICHAEL JAMES PRATT', 'JOSE RODOLFO VILLARREAL-HERNANDEZ', 'RAFAEL CARO-QUINTERO']

In [21]:
display(len(top))

10

In [22]:
top_wanted = pd.DataFrame({"TOP 10":top})
top_wanted

                              TOP 10
0            OMAR ALEXANDER CARDENAS
1                      ALEXIS FLORES
2     BHADRESHKUMAR CHETANBHAI PATEL
3         ALEJANDRO ROSALES CASTILLO
4        YULAN ADONAY ARCHAGA CARIAS
5                      RUJA IGNATOVA
6                    ARNOLDO JIMENEZ
7                MICHAEL JAMES PRATT
8  JOSE RODOLFO VILLARREAL-HERNANDEZ
9               RAFAEL CARO-QUINTERO

#### 3. A list with the different kind of datasets available in data.gov.uk: url = 'https://data.gov.uk/'

In [23]:
url = 'https://www.data.gov.uk/'
response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')

display(response.status_code)
#soup

200

In [24]:
soup.select(" h3 > a")

[<a class="govuk-link" href="/search?filters%5Btopic%5D=Business+and+economy">Business and economy</a>,
 <a class="govuk-link" href="/search?filters%5Btopic%5D=Crime+and+justice">Crime and justice</a>,
 <a class="govuk-link" href="/search?filters%5Btopic%5D=Defence">Defence</a>,
 <a class="govuk-link" href="/search?filters%5Btopic%5D=Education">Education</a>,
 <a class="govuk-link" href="/search?filters%5Btopic%5D=Environment">Environment</a>,
 <a class="govuk-link" href="/search?filters%5Btopic%5D=Government">Government</a>,
 <a class="govuk-link" href="/search?filters%5Btopic%5D=Government+spending">Government spending</a>,
 <a class="govuk-link" href="/search?filters%5Btopic%5D=Health">Health</a>,
 <a class="govuk-link" href="/search?filters%5Btopic%5D=Mapping">Mapping</a>,
 <a class="govuk-link" href="/search?filters%5Btopic%5D=Society">Society</a>,
 <a class="govuk-link" href="/search?filters%5Btopic%5D=Towns+and+cities">Towns and cities</a>,
 <a class="govuk-link" href="/search?filters%5Btopic%5D=Transport">Transport</a>,
 <a class="govuk-link" href="/search?filters%5Btopic%5D=Digital+service+performance">Digital service performance</a>,
 <a class="govuk-link" href="/search?filters%5Btopic%5D=Government+reference+data">Government reference data</a>]

In [25]:
datasets = []

# Iterations
num_iter = len(soup.select("h3 > a"))

data = soup.select("h3 > a")


for i in range(num_iter):
    datasets.append(data[i].get_text())
    
    
print(datasets[0:20])

['Business and economy', 'Crime and justice', 'Defence', 'Education', 'Environment', 'Government', 'Government spending', 'Health', 'Mapping', 'Society', 'Towns and cities', 'Transport', 'Digital service performance', 'Government reference data']

In [26]:
dataset_uk = pd.DataFrame({"datasets":datasets})
dataset_uk

                       datasets
0          Business and economy
1             Crime and justice
2                       Defence
3                     Education
4                   Environment
5                    Government
6           Government spending
7                        Health
8                       Mapping
9                       Society
10             Towns and cities
11                    Transport
12  Digital service performance
13    Government reference data

#### Display the 20 latest earthquakes info (date, time, latitude, longitude and region name) by the EMSC as a pandas dataframe: url = 'https://www.emsc-csem.org/Earthquake/'

In [27]:
url = 'https://www.emsc-csem.org/Earthquake/'
response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')

display(response.status_code)
#soup

200

In [ ]:
# Get date, time, latitude, longitude and region name 

#reg0
# region --> #ong1 > table:nth-child(1) > tbody > tr > td:nth-child(1) > table > tbody > tr:nth-child(2) > td.point2
# date & time --> #ong1 > table:nth-child(1) > tbody > tr > td:nth-child(1) > table > tbody > tr:nth-child(3) > td.point2
# location --> #ong1 > table:nth-child(1) > tbody > tr > td:nth-child(1) > table > tbody > tr:nth-child(5) > td.point2

In [28]:
soup.select("tbody tr td")

[<td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev6"><b><i style="display:none;">earthquake</i><a href="/Earthquake/earthquake.php?id=1242938">2023-03-28   06:08:05.6</a></b><i class="ago" id="ago0">03min ago</i></td>,
 <td class="tabev1">38.23 </td>,
 <td class="tabev2">N  </td>,
 <td class="tabev1">38.81 </td>,
 <td class="tabev2">E  </td>,
 <td class="tabev3">5</td>,
 <td class="tabev5" id="magtyp0">M </td>,
 <td class="tabev2">2.9</td>,
 <td class="tb_region" id="reg0"> EASTERN TURKEY</td>,
 <td class="comment updatetimeno" id="upd0" style="text-align:right;">2023-03-28 06:11</td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev6"><b><i style="display:none;">earthquake</i><a href="/Earthquake/earthquake.php?id=1242935">2023-03-28   05:53:54.3</a></b><i class="ago" id="ago1">17min ago</i></td>,
 <td class="tabev1">37.34 </td>,
 <td class="tabev2">S  </td>,
 <td class="tabev1">177.29 </td>,
 <td class="tabev2">E  </td>,
 <td class="tabev3">5</td>,
 <td class="tabev5" id="magtyp1">ML</td>,
 <td class="tabev2">3.1</td>,
 <td class="tb_region" id="reg1"> OFF E. COAST OF N. ISLAND, N.Z.</td>,
 <td class="comment updatetimeno" id="upd1" style="text-align:right;">2023-03-28 06:05</td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev6"><b><i style="display:none;">earthquake</i><a href="/Earthquake/earthquake.php?id=1242933">2023-03-28   05:51:29.0</a></b><i class="ago" id="ago2">20min ago</i></td>,
 <td class="tabev1">18.34 </td>,
 <td class="tabev2">N  </td>,
 <td class="tabev1">120.45 </td>,
 <td class="tabev2">E  </td>,
 <td class="tabev3">29</td>,
 <td class="tabev5" id="magtyp2">Mw</td>,
 <td class="tabev2">5.3</td>,
 <td class="tb_region" id="reg2"> LUZON, PHILIPPINES</td>,
 <td class="comment updatetimeno" id="upd2" style="text-align:right;">2023-03-28 06:09</td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev6"><b><i style="display:none;">earthquake</i><a href="/Earthquake/earthquake.php?id=1242930">2023-03-28   05:44:38.0</a></b><i class="ago" id="ago3">27min ago</i></td>,
 <td class="tabev1">37.99 </td>,
 <td class="tabev2">N  </td>,
 <td class="tabev1">37.65 </td>,
 <td class="tabev2">E  </td>,
 <td class="tabev3">0</td>,
 <td class="tabev5" id="magtyp3">ML</td>,
 <td class="tabev2">2.6</td>,
 <td class="tb_region" id="reg3"> CENTRAL TURKEY</td>,
 <td class="comment updatetimeno" id="upd3" style="text-align:right;">2023-03-28 06:05</td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev6"><b><i style="display:none;">earthquake</i><a href="/Earthquake/earthquake.php?id=1242937">2023-03-28   05:42:10.0</a></b><i class="ago" id="ago4">29min ago</i></td>,
 <td class="tabev1">23.62 </td>,
 <td class="tabev2">S  </td>,
 <td class="tabev1">69.03 </td>,
 <td class="tabev2">W  </td>,
 <td class="tabev3">95</td>,
 <td class="tabev5" id="magtyp4"> M</td>,
 <td class="tabev2">2.7</td>,
 <td class="tb_region" id="reg4"> ANTOFAGASTA, CHILE</td>,
 <td class="comment updatetimeno" id="upd4" style="text-align:right;">2023-03-28 06:08</td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev6"><b><i style="display:none;">earthquake</i><a href="/Earthquake/earthquake.php?id=1242932">2023-03-28   05:39:10.8</a></b><i class="ago" id="ago5">32min ago</i></td>,
 <td class="tabev1">17.95 </td>,
 <td class="tabev2">N  </td>,
 <td class="tabev1">66.96 </td>,
 <td class="tabev2">W  </td>,
 <td class="tabev3">16</td>,
 <td class="tabev5" id="magtyp5">Md</td>,
 <td class="tabev2">2.6</td>,
 <td class="tb_region" id="reg5"> PUERTO RICO</td>,
 <td class="comment updatetimeno" id="upd5" style="text-align:right;">2023-03-28 05:49</td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev6"><b><i style="display:none;">earthquake</i><a href="/Earthquake/earthquake.php?id=1242929">2023-03-28   05:28:41.0</a></b><i class="ago" id="ago6">43min ago</i></td>,
 <td class="tabev1">3.92 </td>,
 <td class="tabev2">S  </td>,
 <td class="tabev1">133.67 </td>,
 <td class="tabev2">E  </td>,
 <td class="tabev3">10</td>,
 <td class="tabev5" id="magtyp6"> M</td>,
 <td class="tabev2">3.6</td>,
 <td class="tb_region" id="reg6"> PAPUA, INDONESIA</td>,
 <td class="comment updatetimeno" id="upd6" style="text-align:right;">2023-03-28 05:35</td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev6"><b><i style="display:none;">earthquake</i><a href="/Earthquake/earthquake.php?id=1242925">2023-03-28   05:22:02.6</a></b><i class="ago" id="ago7">49min ago</i></td>,
 <td class="tabev1">38.26 </td>,
 <td class="tabev2">N  </td>,
 <td class="tabev1">37.72 </td>,
 <td class="tabev2">E  </td>,
 <td class="tabev3">5</td>,
 <td class="tabev5" id="magtyp7">M </td>,
 <td class="tabev2">2.6</td>,
 <td class="tb_region" id="reg7"> CENTRAL TURKEY</td>,
 <td class="comment updatetimeno" id="upd7" style="text-align:right;">2023-03-28 05:51</td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev6"><b><i style="display:none;">earthquake</i><a href="/Earthquake/earthquake.php?id=1242926">2023-03-28   05:19:14.0</a></b><i class="ago" id="ago8">52min ago</i></td>,
 <td class="tabev1">3.84 </td>,
 <td class="tabev2">S  </td>,
 <td class="tabev1">133.55 </td>,
 <td class="tabev2">E  </td>,
 <td class="tabev3">14</td>,
 <td class="tabev5" id="magtyp8"> M</td>,
 <td class="tabev2">3.9</td>,
 <td class="tb_region" id="reg8"> PAPUA, INDONESIA</td>,
 <td class="comment updatetimeno" id="upd8" style="text-align:right;">2023-03-28 05:25</td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev6"><b><i style="display:none;">earthquake</i><a href="/Earthquake/earthquake.php?id=1242927">2023-03-28   05:17:02.0</a></b><i class="ago" id="ago9">54min ago</i></td>,
 <td class="tabev1">35.64 </td>,
 <td class="tabev2">N  </td>,
 <td class="tabev1">77.80 </td>,
 <td class="tabev2">E  </td>,
 <td class="tabev3">105</td>,
 <td class="tabev5" id="magtyp9"> M</td>,
 <td class="tabev2">4.3</td>,
 <td class="tb_region" id="reg9"> KASHMIR-XINJIANG BORDER REGION</td>,
 <td class="comment updatetimeno" id="upd9" style="text-align:right;">2023-03-28 05:30</td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev6"><b><i style="display:none;">earthquake</i><a href="/Earthquake/earthquake.php?id=1242921">2023-03-28   04:56:02.7</a></b><i class="ago" id="ago10">1hr 15min ago</i></td>,
 <td class="tabev1">47.35 </td>,
 <td class="tabev2">N  </td>,
 <td class="tabev1">6.91 </td>,
 <td class="tabev2">E  </td>,
 <td class="tabev3">2</td>,
 <td class="tabev5" id="magtyp10">ML</td>,
 <td class="tabev2">1.8</td>,
 <td class="tb_region" id="reg10"> FRANCE</td>,
 <td class="comment updatetimeno" id="upd10" style="text-align:right;">2023-03-28 05:04</td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev6"><b><i style="display:none;">earthquake</i><a href="/Earthquake/earthquake.php?id=1242920">2023-03-28   04:48:20.3</a></b><i class="ago" id="ago11">1hr 23min ago</i></td>,
 <td class="tabev1">38.08 </td>,
 <td class="tabev2">N  </td>,
 <td class="tabev1">36.96 </td>,
 <td class="tabev2">E  </td>,
 <td class="tabev3">10</td>,
 <td class="tabev5" id="magtyp11">M </td>,
 <td class="tabev2">2.6</td>,
 <td class="tb_region" id="reg11"> CENTRAL TURKEY</td>,
 <td class="comment updatetimeno" id="upd11" style="text-align:right;">2023-03-28 05:45</td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev6"><b><i style="display:none;">earthquake</i><a href="/Earthquake/earthquake.php?id=1242923">2023-03-28   04:39:12.0</a></b><i class="ago" id="ago12">1hr 32min ago</i></td>,
 <td class="tabev1">16.11 </td>,
 <td class="tabev2">N  </td>,
 <td class="tabev1">95.56 </td>,
 <td class="tabev2">W  </td>,
 <td class="tabev3">7</td>,
 <td class="tabev5" id="magtyp12"> M</td>,
 <td class="tabev2">4.0</td>,
 <td class="tb_region" id="reg12"> OAXACA, MEXICO</td>,
 <td class="comment updatetimeno" id="upd12" style="text-align:right;">2023-03-28 05:05</td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev6"><b><i style="display:none;">earthquake</i><a href="/Earthquake/earthquake.php?id=1242919">2023-03-28   04:37:41.9</a></b><i class="ago" id="ago13">1hr 34min ago</i></td>,
 <td class="tabev1">40.70 </td>,
 <td class="tabev2">N  </td>,
 <td class="tabev1">42.76 </td>,
 <td class="tabev2">E  </td>,
 <td class="tabev3">6</td>,
 <td class="tabev5" id="magtyp13">ML</td>,
 <td class="tabev2">2.1</td>,
 <td class="tb_region" id="reg13"> EASTERN TURKEY</td>,
 <td class="comment updatetimeno" id="upd13" style="text-align:right;">2023-03-28 04:46</td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev6"><b><i style="display:none;">earthquake</i><a href="/Earthquake/earthquake.php?id=1242918">2023-03-28   04:31:48.3</a></b><i class="ago" id="ago14">1hr 40min ago</i></td>,
 <td class="tabev1">3.65 </td>,
 <td class="tabev2">S  </td>,
 <td class="tabev1">139.11 </td>,
 <td class="tabev2">E  </td>,
 <td class="tabev3">10</td>,
 <td class="tabev5" id="magtyp14">mb</td>,
 <td class="tabev2">4.2</td>,
 <td class="tb_region" id="reg14"> PAPUA, INDONESIA</td>,
 <td class="comment updatetimeno" id="upd14" style="text-align:right;">2023-03-28 06:04</td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev6"><b><i style="display:none;">earthquake</i><a href="/Earthquake/earthquake.php?id=1242917">2023-03-28   04:26:13.0</a></b><i class="ago" id="ago15">1hr 45min ago</i></td>,
 <td class="tabev1">8.44 </td>,
 <td class="tabev2">S  </td>,
 <td class="tabev1">121.14 </td>,
 <td class="tabev2">E  </td>,
 <td class="tabev3">175</td>,
 <td class="tabev5" id="magtyp15"> M</td>,
 <td class="tabev2">3.0</td>,
 <td class="tb_region" id="reg15"> FLORES REGION, INDONESIA</td>,
 <td class="comment updatetimeno" id="upd15" style="text-align:right;">2023-03-28 04:35</td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev6"><b><i style="display:none;">earthquake</i><a href="/Earthquake/earthquake.php?id=1242912">2023-03-28   04:19:10.7</a></b><i class="ago" id="ago16">1hr 52min ago</i></td>,
 <td class="tabev1">0.38 </td>,
 <td class="tabev2">S  </td>,
 <td class="tabev1">123.59 </td>,
 <td class="tabev2">E  </td>,
 <td class="tabev3">80</td>,
 <td class="tabev5" id="magtyp16">Mw</td>,
 <td class="tabev2">5.0</td>,
 <td class="tb_region" id="reg16"> SULAWESI, INDONESIA</td>,
 <td class="comment updatetimeno" id="upd16" style="text-align:right;">2023-03-28 05:40</td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev6"><b><i style="display:none;">earthquake</i><a href="/Earthquake/earthquake.php?id=1242910">2023-03-28   04:16:26.7</a></b><i class="ago" id="ago17">1hr 55min ago</i></td>,
 <td class="tabev1">37.75 </td>,
 <td class="tabev2">N  </td>,
 <td class="tabev1">37.60 </td>,
 <td class="tabev2">E  </td>,
 <td class="tabev3">10</td>,
 <td class="tabev5" id="magtyp17">M </td>,
 <td class="tabev2">2.9</td>,
 <td class="tb_region" id="reg17"> CENTRAL TURKEY</td>,
 <td class="comment updatetimeno" id="upd17" style="text-align:right;">2023-03-28 04:44</td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev6"><b><i style="display:none;">earthquake</i><a href="/Earthquake/earthquake.php?id=1242911">2023-03-28   04:14:02.2</a></b><i class="ago" id="ago18">1hr 57min ago</i></td>,
 <td class="tabev1">38.35 </td>,
 <td class="tabev2">N  </td>,
 <td class="tabev1">37.19 </td>,
 <td class="tabev2">E  </td>,
 <td class="tabev3">6</td>,
 <td class="tabev5" id="magtyp18">ML</td>,
 <td class="tabev2">2.0</td>,
 <td class="tb_region" id="reg18"> CENTRAL TURKEY</td>,
 <td class="comment updatetimeno" id="upd18" style="text-align:right;">2023-03-28 04:20</td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev6"><b><i style="display:none;">earthquake</i><a href="/Earthquake/earthquake.php?id=1242915">2023-03-28   04:12:00.6</a></b><i class="ago" id="ago19">1hr 59min ago</i></td>,
 <td class="tabev1">19.03 </td>,
 <td class="tabev2">N  </td>,
 <td class="tabev1">67.15 </td>,
 <td class="tabev2">W  </td>,
 <td class="tabev3">8</td>,
 <td class="tabev5" id="magtyp19">Md</td>,
 <td class="tabev2">3.3</td>,
 <td class="tb_region" id="reg19"> PUERTO RICO REGION</td>,
 <td class="comment updatetimeno" id="upd19" style="text-align:right;">2023-03-28 04:32</td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev6"><b><i style="display:none;">earthquake</i><a href="/Earthquake/earthquake.php?id=1242907">2023-03-28   04:05:00.1</a></b><i class="ago" id="ago20">2hr 06min ago</i></td>,
 <td class="tabev1">39.41 </td>,
 <td class="tabev2">N  </td>,
 <td class="tabev1">123.34 </td>,
 <td class="tabev2">W  </td>,
 <td class="tabev3">5</td>,
 <td class="tabev5" id="magtyp20">MD</td>,
 <td class="tabev2">2.5</td>,
 <td class="tb_region" id="reg20"> NORTHERN CALIFORNIA</td>,
 <td class="comment updatetimeno" id="upd20" style="text-align:right;">2023-03-28 04:06</td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev6"><b><i style="display:none;">earthquake</i><a href="/Earthquake/earthquake.php?id=1242909">2023-03-28   04:04:22.6</a></b><i class="ago" id="ago21">2hr 07min ago</i></td>,
 <td class="tabev1">37.46 </td>,
 <td class="tabev2">N  </td>,
 <td class="tabev1">37.13 </td>,
 <td class="tabev2">E  </td>,
 <td class="tabev3">2</td>,
 <td class="tabev5" id="magtyp21">ML</td>,
 <td class="tabev2">2.2</td>,
 <td class="tb_region" id="reg21"> CENTRAL TURKEY</td>,
 <td class="comment updatetimeno" id="upd21" style="text-align:right;">2023-03-28 04:11</td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev6"><b><i style="display:none;">earthquake</i><a href="/Earthquake/earthquake.php?id=1242908">2023-03-28   04:02:12.5</a></b><i class="ago" id="ago22">2hr 09min ago</i></td>,
 <td class="tabev1">38.03 </td>,
 <td class="tabev2">N  </td>,
 <td class="tabev1">36.54 </td>,
 <td class="tabev2">E  </td>,
 <td class="tabev3">3</td>,
 <td class="tabev5" id="magtyp22">ML</td>,
 <td class="tabev2">2.2</td>,
 <td class="tb_region" id="reg22"> CENTRAL TURKEY</td>,
 <td class="comment updatetimeno" id="upd22" style="text-align:right;">2023-03-28 04:09</td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev6"><b><i style="display:none;">earthquake</i><a href="/Earthquake/earthquake.php?id=1242905">2023-03-28   03:43:59.0</a></b><i class="ago" id="ago23">2hr 27min ago</i></td>,
 <td class="tabev1">10.26 </td>,
 <td class="tabev2">S  </td>,
 <td class="tabev1">119.33 </td>,
 <td class="tabev2">E  </td>,
 <td class="tabev3">10</td>,
 <td class="tabev5" id="magtyp23"> M</td>,
 <td class="tabev2">3.2</td>,
 <td class="tb_region" id="reg23"> SUMBA REGION, INDONESIA</td>,
 <td class="comment updatetimeno" id="upd23" style="text-align:right;">2023-03-28 03:50</td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev6"><b><i style="display:none;">earthquake</i><a href="/Earthquake/earthquake.php?id=1242904">2023-03-28   03:37:40.8</a></b><i class="ago" id="ago24">2hr 34min ago</i></td>,
 <td class="tabev1">38.10 </td>,
 <td class="tabev2">N  </td>,
 <td class="tabev1">37.20 </td>,
 <td class="tabev2">E  </td>,
 <td class="tabev3">6</td>,
 <td class="tabev5" id="magtyp24">ML</td>,
 <td class="tabev2">2.2</td>,
 <td class="tb_region" id="reg24"> CENTRAL TURKEY</td>,
 <td class="comment updatetimeno" id="upd24" style="text-align:right;">2023-03-28 03:49</td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev6"><b><i style="display:none;">earthquake</i><a href="/Earthquake/earthquake.php?id=1242899">2023-03-28   03:37:22.0</a></b><i class="ago" id="ago25">2hr 34min ago</i></td>,
 <td class="tabev1">45.85 </td>,
 <td class="tabev2">N  </td>,
 <td class="tabev1">7.04 </td>,
 <td class="tabev2">E  </td>,
 <td class="tabev3">2</td>,
 <td class="tabev5" id="magtyp25">ML</td>,
 <td class="tabev2">1.8</td>,
 <td class="tb_region" id="reg25"> NORTHERN ITALY</td>,
 <td class="comment updatetimeno" id="upd25" style="text-align:right;">2023-03-28 03:44</td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev6"><b><i style="display:none;">earthquake</i><a href="/Earthquake/earthquake.php?id=1242898">2023-03-28   03:26:29.2</a></b><i class="ago" id="ago26">2hr 45min ago</i></td>,
 <td class="tabev1">19.39 </td>,
 <td class="tabev2">N  </td>,
 <td class="tabev1">155.27 </td>,
 <td class="tabev2">W  </td>,
 <td class="tabev3">28</td>,
 <td class="tabev5" id="magtyp26">Ml</td>,
 <td class="tabev2">2.1</td>,
 <td class="tb_region" id="reg26"> ISLAND OF HAWAII, HAWAII</td>,
 <td class="comment updatetimeno" id="upd26" style="text-align:right;">2023-03-28 03:32</td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev6"><b><i style="display:none;">earthquake</i><a href="/Earthquake/earthquake.php?id=1242902">2023-03-28   03:23:08.1</a></b><i class="ago" id="ago27">2hr 48min ago</i></td>,
 <td class="tabev1">37.92 </td>,
 <td class="tabev2">N  </td>,
 <td class="tabev1">36.31 </td>,
 <td class="tabev2">E  </td>,
 <td class="tabev3">5</td>,
 <td class="tabev5" id="magtyp27">ML</td>,
 <td class="tabev2">2.0</td>,
 <td class="tb_region" id="reg27"> CENTRAL TURKEY</td>,
 <td class="comment updatetimeno" id="upd27" style="text-align:right;">2023-03-28 03:46</td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev6"><b><i style="display:none;">earthquake</i><a href="/Earthquake/earthquake.php?id=1242901">2023-03-28   03:17:01.5</a></b><i class="ago" id="ago28">2hr 54min ago</i></td>,
 <td class="tabev1">17.81 </td>,
 <td class="tabev2">S  </td>,
 <td class="tabev1">167.45 </td>,
 <td class="tabev2">E  </td>,
 <td class="tabev3">10</td>,
 <td class="tabev5" id="magtyp28">mb</td>,
 <td class="tabev2">4.7</td>,
 <td class="tb_region" id="reg28"> VANUATU</td>,
 <td class="comment updatetimeno" id="upd28" style="text-align:right;">2023-03-28 06:01</td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev6"><b><i style="display:none;">earthquake</i><a href="/Earthquake/earthquake.php?id=1242897">2023-03-28   03:07:50.0</a></b><i class="ago" id="ago29">3hr 03min ago</i></td>,
 <td class="tabev1">33.61 </td>,
 <td class="tabev2">S  </td>,
 <td class="tabev1">71.32 </td>,
 <td class="tabev2">W  </td>,
 <td class="tabev3">61</td>,
 <td class="tabev5" id="magtyp29"> M</td>,
 <td class="tabev2">2.7</td>,
 <td class="tb_region" id="reg29"> VALPARAISO, CHILE</td>,
 <td class="comment updatetimeno" id="upd29" style="text-align:right;">2023-03-28 03:24</td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev0"></td>,
 <td class="tabev6"><b><i style="display:none;">earthquake</i><a href="/Earthquake/earthquake.php?id=1242892">2023-03-28   03:04:39.4</a></b><i class="ago" id="ago30">3hr 07min ago</i></td>,
 <td class="tabev1">36.09 </td>,
 <td class="tabev2">N  </td>,
 <td class="tabev1">35.89 </td>,
 <td class="tabev2">E  </td>,
 <td class="tabev3">8</td>,
 <td class="tabev5" id="magtyp30">ML</td>,
 <td class="tabev2">2.7</td>,

In [29]:
region_list = []

# Iterations
num_iter = len(soup.select("tbody tr td"))

region = soup.select("tbody tr td")


for i in range(num_iter):
    region_list.append(region[i].get_text())
    
    
print(region_list[0:20])

['', '', '', 'earthquake2023-03-28\xa0\xa0\xa006:08:05.603min ago', '38.23\xa0', 'N\xa0\xa0', '38.81\xa0', 'E\xa0\xa0', '5', 'M ', '2.9', '\xa0EASTERN TURKEY', '2023-03-28 06:11', '', '', '', 'earthquake2023-03-28\xa0\xa0\xa005:53:54.317min ago', '37.34\xa0', 'S\xa0\xa0', '177.29\xa0']

#### Attempt with links.........

#### Display the 20 latest earthquakes info (date, time, latitude, longitude and region name) by the EMSC as a pandas dataframe: url = 'https://www.emsc-csem.org/Earthquake/'

In [ ]:
url = 'https://www.emsc-csem.org/Earthquake/'
response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')

display(response.status_code)
#soup

In [ ]:
# link --> #\31 242674 > td.tabev6 > b > a

In [ ]:
prestab=soup.select("b a")
prestab[0:5]

In [ ]:
# Getting links for the 20 most recent earthquakes
earthquake = []

for quake in prestab:
    link = quake.get("href")
    print(link)
    if(len(earthquake)<20):
        if link is not None:
            if (("/Earthquake" in link) & ("earthquake" in link)):
                earthquake.append(quake["href"])
    else:
        break

In [ ]:
display(len(earthquake))

In [ ]:
# Creating full URL for each earthquake and sending requests
url = "https://www.emsc-csem.org" + earthquake[0]
response = requests.get(url)
print(response.status_code)

In [ ]:
# Parse & store html
soup = BeautifulSoup(response.content, "html.parser")
#soup.select("table")

In [ ]:
# Links for latest 20 earthquake --> earthquakes

# 2. Finding url and store it in a variable
quake_soups = []

for quake in earthquake:
    # send request
    url =  "https://www.emsc-csem.org" + quake
    response = requests.get(url)
    print(quake, response.status_code)

    # parse & store html
    soup = BeautifulSoup(response.content, "html.parser")
    quake_soups.append(soup.select("table"))

    # respectful nap:
    wait_time = random.randint(1,4)
    print("I will sleep for " + str(wait_time) + " second/s.")
    sleep(wait_time)

In [ ]:
quake_soups

In [ ]:
# Get date, time, latitude, longitude and region name AND MAGNITUDE...

# magnitude --> #ong1 > table:nth-child(1) > tbody > tr > td:nth-child(1) > table > tbody > tr:nth-child(1) > td.point2
# region --> #ong1 > table:nth-child(1) > tbody > tr > td:nth-child(1) > table > tbody > tr:nth-child(2) > td.point2
# date & time --> #ong1 > table:nth-child(1) > tbody > tr > td:nth-child(1) > table > tbody > tr:nth-child(3) > td.point2
# location --> #ong1 > table:nth-child(1) > tbody > tr > td:nth-child(1) > table > tbody > tr:nth-child(5) > td.point2

In [ ]:
quake_soups[-1][0].select("td.point2")

# ?

- List all language names and number of related articles in the order they appear in wikipedia.org: url = 'https://www.wikipedia.org/'
- 
- Display the top 10 languages by number of native speakers stored in a pandas dataframe: url = 'https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers'